#ifndef ANSI_COLOR_H
#define ANSI_COLOR_H

#define ANSI_RESET			"\033[0m"
#define ANSI_BLACK			"\033[0;30m"
#define ANSI_RED			"\033[0;31m"
#define ANSI_GREEN			"\033[0;32m"
#define ANSI_ORANGE			"\033[0;33m"
#define ANSI_BLUE			"\033[0;34m"
#define ANSI_PURPLE			"\033[0;35m"
#define ANSI_CYAN			"\033[0;36m"
#define ANSI_LIGHTGRAY		"\033[0;37m"
#define ANSI_DARKGRAY		"\033[1;30m"
#define ANSI_LIGHTRED		"\033[1;31m"
#define ANSI_LIGHTGREEN		"\033[1;32m"
#define ANSI_YELLOW			"\033[1;33m"
#define ANSI_LIGHTBLUE		"\033[1;34m"
#define ANSI_LIGHTPURPLE	"\033[1;35m"
#define ANSI_LIGHTCYAN		"\033[1;36m"
#define ANSI_WHITE			"\033[1;37m"

#define ANSI_COLORS_COUNT	17

#define ANSI_COLORS { \
	ANSI_RESET, ANSI_BLACK, ANSI_RED, ANSI_GREEN, ANSI_ORANGE, \
	ANSI_BLUE, ANSI_PURPLE, ANSI_CYAN, ANSI_LIGHTGRAY, ANSI_DARKGRAY, \
	ANSI_LIGHTRED, ANSI_LIGHTGREEN, ANSI_YELLOW, ANSI_LIGHTBLUE, ANSI_LIGHTPURPLE, \
	ANSI_LIGHTCYAN, ANSI_WHITE \
}

typedef enum e_ansi_color {
	COLOR_RESET,
	COLOR_BLACK,
	COLOR_RED,
	COLOR_GREEN,
	COLOR_ORANGE,
	COLOR_BLUE,
	COLOR_PURPLE,
	COLOR_CYAN,
	COLOR_LIGHTGRAY,
	COLOR_DARKGRAY,
	COLOR_LIGHTRED,
	COLOR_LIGHTGREEN,
	COLOR_YELLOW,
	COLOR_LIGHTBLUE,
	COLOR_LIGHTPURPLE,
	COLOR_LIGHTCYAN,
	COLOR_WHITE
} t_ansi_color;

void	disable_colors();
void	enable_colors();
char	*get_color(t_ansi_color color);

#endif